### PR TITLE
Replace crypto:rand_uniform/2 with rand:uniform/1

### PR DESCRIPTION
**Pull request by kyle-neal**
Simple change to make gen_smtp compliant with OTP 20+

### CODE REVIEW

**Comment by seriyps** [comment]
But it makes it incompatible with OTP < 18.

**Comment by seriyps** [comment]
Plus there is no such function as `rand:uniform/2`. Only `rand:uniform/1` http://erlang.org/doc/man/rand.html#uniform-1.

You may try to use `crypto` module: http://erlang.org/doc/man/crypto.html#rand_uniform-2

**Comment by mworrell** [comment]
@Vagabond @arjan would you be ok to drop support for R16B and OTP-17?

I am ok with that, as OTP 21 has been released already.

**Comment by mworrell** [comment]
Closing this and not merging, as the function `rand:uniform/2` does not exist.

**Pull request closed without merging**
