### PR TITLE
Update smtp_util.erl

### PR DESCRIPTION
**Pull request by Gertm**
Tried this with Erlang R16B02 and it failed to compile, this fixes it.

### CODE REVIEW

**Comment by kaos** [comment]
And now R18.0 is out.. :)

**Comment by mworrell** [comment]
@Vagabond Ready to drop R15 support?

**Comment by JustMikey** [comment]
@Vagabond R18 is out so if you plan to support only last two major releases, it's time to drop the support for R15.

**Comment by Vagabond** [comment]
I would rather see only supporting the last 2 major releases, so yes.

**Comment by JustMikey** [comment]
@Vagabond The change has been merged from another PR, this can be also closed.

**Comment by arjan** [comment]
Outdated indeed, we moved to support R16 and up only.

**Pull request closed without merging**
