### PR TITLE
Added case for handling empty body

### PR DESCRIPTION
**Pull request by KoFish**

### CODE REVIEW

**Comment by seriyps** [comment]
Looks good.
Without that case expression `FilteredSize / Size` will fall with `badarith` (division by zero).

**Comment by mworrell** [comment]
Following the logic of the case below the change, wouldn't `7bit` be a more logical encoding?

**Comment by KoFish** [comment]
Thanks, that makes very much sense yes :)

**Comment by mworrell** [comment]
@KoFish thanks!

**Pull request merged**
