### PR TITLE
Rename 'socket' to 'smtp_socket'

### LINKED ISSUE #168: Conflict with Erlang/OTP-22 socket module
Erlang/OTP-22 is introducing a new module called "socket", documented here (as of 22-rc2): 

http://erlang.org/documentation/doc-11.0-rc2/erts-10.4/doc/html/socket.html

This module conflicts with the module called "socket" in gen_smtp, preventing us from using the library when running on 22-rc2 (undefined function error for socket:connect/5). Would it be possible to rename the module to something like "gen_smtp_socket" perhaps?

### PR DESCRIPTION
**Pull request by mworrell**
This fixes compatibility with OTP-22 which introduces a socket module.

Fixes #168

### CODE REVIEW

**Comment by seriyps** [comment]
Looks good for me.

ср, 3 апр. 2019 г., 9:47 Marc Worrell <notifications@github.com>:

**Comment by mworrell** [comment]
All tests pass as well. Waiting for a review ,though I think it is safe to merge.

**Comment by mworrell** [comment]
@arjan @Vagabond If you don't have any problems then I will merge this.

**Comment by Vagabond** [comment]
Looks alright to me

**Comment by mworrell** [comment]
Thanks!  Merging.

**Pull request merged**
